In [8]:
import numpy as np
import pandas as pd

In [9]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [12]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
matriz[1][2]

6

In [14]:
matriz[1][2] *5

30

In [15]:
matriz [0][:]

array([1, 2, 3])

In [16]:
matriz [0][1:]

array([2, 3])

In [17]:
matriz [1][:2]

array([4, 5])

In [18]:
np.arange(1,26, 0.2)

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8])

In [19]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [20]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
matriz2 = np.arange(1,26).reshape(5,5)

In [22]:
print(matriz2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
matriz2 [2][1:4]

array([12, 13, 14])

In [24]:
matriz2[2:4, 3]

array([14, 19])

# CALCULO DE POTENCIA
$4 ^ 5$

In [26]:
np.power(4,5)

1024

# Calculo de raiz quadrada
$\sqrt81$

In [28]:
np.sqrt(81)

9.0

In [29]:
A = np.array([[1,2,1],[1,-3,5],[2,-1,3]])
b = np.array([12,1,10])
np.linalg.solve(A,b)

array([5., 3., 1.])

# multiplicacao de matrizes

In [31]:
A = np.array([[1,2,1],[1,-3,5],[2,-1,3]])
B = np.array([[8,0,1],[-1,2,4],[0,-1,7]])

In [32]:
print(A)

[[ 1  2  1]
 [ 1 -3  5]
 [ 2 -1  3]]


In [33]:
print(B)

[[ 8  0  1]
 [-1  2  4]
 [ 0 -1  7]]


In [34]:
np.matmul(A,B)

array([[  6,   3,  16],
       [ 11, -11,  24],
       [ 17,  -5,  19]])

In [35]:
A*B # = np.multiply

array([[ 8,  0,  1],
       [-1, -6, 20],
       [ 0,  1, 21]])

In [36]:
A + B

array([[ 9,  2,  2],
       [ 0, -1,  9],
       [ 2, -2, 10]])

In [37]:
A - B

array([[-7,  2,  0],
       [ 2, -5,  1],
       [ 2,  0, -4]])

In [38]:
A @ B  # = np.matmul

array([[  6,   3,  16],
       [ 11, -11,  24],
       [ 17,  -5,  19]])

# CRIAR MATRIZES DE 0 E 1

In [40]:
np.zeros(4)

array([0., 0., 0., 0.])

In [41]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.eye(4)  # matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# NUMEROS ALEATORIOS

In [45]:
np.random.randint(1,300)

251

In [46]:
np.random.standard_normal()

1.4029098755905645

# TUPLAS E DICIONARIOS

## TUPLAS

In [49]:
dias_semana = ('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo') #tuplas () não se alteram

In [50]:
lista_dias_semana = ['segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo'] # LISTA [] se altera

In [51]:
lista_dias_semana[0] = 'segunda alterada'

In [52]:
lista_dias_semana [0]

'segunda alterada'

## DICIONARIO

In [54]:
#{} E VALORES

In [55]:
array_notas = np.zeros(4)
print(array_notas)
for i in range(len(array_notas)):
    array_notas[i] = np.random.randint(4,10)
print(array_notas)

[0. 0. 0. 0.]
[4. 8. 7. 7.]


In [56]:
alunos = {'Alunos': ['Aluno1', 'Aluno2', 'Aluno3', 'Aluno4'], 'Notas':array_notas}

In [57]:
alunos

{'Alunos': ['Aluno1', 'Aluno2', 'Aluno3', 'Aluno4'],
 'Notas': array([4., 8., 7., 7.])}

In [58]:
alunos.keys()

dict_keys(['Alunos', 'Notas'])

In [59]:
for chave in alunos.keys():
    print (alunos[chave])

['Aluno1', 'Aluno2', 'Aluno3', 'Aluno4']
[4. 8. 7. 7.]


In [60]:
for i in range(len(alunos['Alunos'])):
    print(f"O aluno {alunos['Alunos'][i]} possui a nota {alunos['Notas'][i]}")

O aluno Aluno1 possui a nota 4.0
O aluno Aluno2 possui a nota 8.0
O aluno Aluno3 possui a nota 7.0
O aluno Aluno4 possui a nota 7.0


In [61]:
from Funcoes import utilizacaoContrato

In [62]:
utilizacaoContrato(10000, 500, 1000)

Contrato em Andamento, uso entre 5% e 90%


(15.0, 8500)